"""Generate the terminal hero SVGs for the GitHub profile README.

The KALAGN mark is a hand-placed 5x7 dot matrix: one <rect> per lit pixel.
Edit FONT/GLYPH here and re-run `python build_hero.py`; never hand-edit the SVGs.
"""
from pathlib import Path

FONT = {
    "K": ["#...#", "#..#.", "#.#..", "##...", "#.#..", "#..#.", "#...#"],
    "A": [".###.", "#...#", "#...#", "#####", "#...#", "#...#", "#...#"],
    "L": ["#....", "#....", "#....", "#....", "#....", "#....", "#####"],
    "G": [".###.", "#...#", "#....", "#..##", "#...#", "#...#", ".###."],
    "N": ["#...#", "##..#", "##..#", "#.#.#", "#..##", "#..##", "#...#"],
}
PITCH, CELL, GLYPH_GAP = 14, 11, 6
ROLES = [
    ("RAG · retrieval systems (t-rag)", 300),
    ("Go &amp; PHP backend · 30 public repos", 372),
    ("local-first tooling · Python · Java", 356),
    ("Do not go gentle into that good night", 336),
]

DARK = dict(bg="#0d1117", panel="#0c111a", border="#1e2735", grid=".055",
            c1="#8b5cf6", c2="#c4b5fd", c3="#22d3ee", dim="#7488a0",
            body="#d6e0ee", user="#22d3ee", prompt="#8b5cf6")
LIGHT = dict(bg="#ffffff", panel="#f6f8fa", border="#d0d7de", grid=".07",
             c1="#7c3aed", c2="#a78bfa", c3="#0891b2", dim="#57606a",
             body="#24292f", user="#0891b2", prompt="#7c3aed")


def matrix(text: str, x0: int, y0: int) -> tuple[str, int]:
    rects, col = [], 0
    for char in text:
        for row, line in enumerate(FONT[char]):
            for offset, lit in enumerate(line):
                if lit == "#":
                    rects.append(
                        f'    <rect x="{x0 + (col + offset) * PITCH}" y="{y0 + row * PITCH}" '
                        f'width="{CELL}" height="{CELL}" rx="2"/>'
                    )
        col += GLYPH_GAP
    return "\n".join(rects), x0 + (col - 1) * PITCH + CELL


def build(theme: dict, word: str = "KALAGN") -> str:
    rects, _ = matrix(word, 48, 40)
    roles = "\n".join(
        f'    <text class="r{i + 1}" x="214" y="232" textLength="{width}" '
        f'lengthAdjust="spacingAndGlyphs">{text}</text>'
        for i, (text, width) in enumerate(ROLES)
    )
    delays = " ".join(f".r{i + 1}{{animation-delay:{i * 4}s!important}}" for i in range(len(ROLES)))
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 296" font-family="ui-monospace,'SF Mono',Menlo,Consolas,monospace">
  <!--
    Terminal hero for @kalaGN  ( repo: kalaGN/kalaGN , file: assets/hero-*.svg )
    Theme "Night Terminal" - violet {theme["c1"]} + cyan {theme["c3"]} on {theme["bg"]}.
    Re colour by find/replace of those two hex codes.
    Generated by build_hero.py - the KALAGN mark is a 5x7 dot matrix,
    one <rect> per lit pixel at {PITCH}px pitch / {CELL}px cell.
  -->
  <defs>
    <linearGradient id="mark" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{theme["c1"]}"/><stop offset=".45" stop-color="{theme["c2"]}"/><stop offset="1" stop-color="{theme["c3"]}"/>
    </linearGradient>
    <linearGradient id="edge" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="{theme["c1"]}"/><stop offset="1" stop-color="{theme["c3"]}"/>
    </linearGradient>
    <filter id="glow" x="-30%" y="-30%" width="160%" height="160%">
      <feGaussianBlur stdDeviation="4" result="b"/>
      <feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
    <pattern id="grid" width="36" height="36" patternUnits="userSpaceOnUse">
      <path d="M36 0H0V36" fill="none" stroke="{theme["c1"]}" stroke-opacity="{theme["grid"]}"/>
    </pattern>
  </defs>
  <style>
    .roles text{{opacity:0; animation:cyc 16s linear infinite}}
    {delays}
    @keyframes cyc{{0%{{opacity:0}}3%,20%{{opacity:1}}24%,100%{{opacity:0}}}}
    .caret{{animation:blink 1s steps(1) infinite}}
    @keyframes blink{{50%{{opacity:0}}}}
    .pulse{{animation:pulse 2.4s ease-in-out infinite}}
    @keyframes pulse{{50%{{opacity:.35}}}}
  </style>
  <rect x="8" y="8" width="984" height="280" rx="14" fill="{theme["bg"]}"/>
  <rect x="8" y="8" width="984" height="280" rx="14" fill="url(#grid)"/>
  <rect x="8.5" y="8.5" width="983" height="279" rx="13.5" fill="none" stroke="{theme["border"]}"/>
  <rect x="9" y="9" width="982" height="2" fill="url(#edge)" opacity=".5"/>

  <g fill="url(#mark)" filter="url(#glow)">
{rects}
  </g>
  <line x1="704" y1="44" x2="704" y2="252" stroke="{theme["border"]}"/>
  <text x="50" y="188" font-size="13" letter-spacing="6" fill="{theme["c3"]}" opacity=".9">D O · N O T · G O · G E N T L E</text>
  <text x="48" y="272" font-size="12" fill="{theme["dim"]}">30 public repos · Go / PHP / Python / Java · blog: cnblogs.com/kala00k</text>

  <rect x="48" y="206" width="648" height="44" rx="8" fill="{theme["panel"]}" stroke="{theme["border"]}"/>
  <text x="66" y="233" font-size="15" textLength="140" lengthAdjust="spacingAndGlyphs"><tspan fill="{theme["user"]}">afei</tspan><tspan fill="{theme["prompt"]}">@github:~$</tspan></text>
  <g class="roles" font-size="15" fill="{theme["body"]}">
{roles}
  </g>
  <rect class="caret" x="678" y="218" width="9" height="20" fill="{theme["c3"]}"/>

  <g font-size="13">
    <circle class="pulse" cx="740" cy="227" r="5" fill="{theme["c3"]}"/>
    <text x="754" y="232" fill="{theme["dim"]}">status: <tspan fill="{theme["c1"]}">building</tspan></text>
    <text x="724" y="72" fill="{theme["dim"]}">focus</text>
    <text x="724" y="98" fill="{theme["c1"]}" font-size="17" font-weight="700">Retrieval</text>
    <text x="724" y="124" fill="{theme["c3"]}" font-size="17" font-weight="700">Local-first RAG</text>
    <text x="724" y="158" fill="{theme["dim"]}">stack</text>
    <text x="724" y="182" fill="{theme["body"]}" font-size="15">Go · PHP</text>
    <text x="724" y="204" fill="{theme["body"]}" font-size="15">Python · Java</text>
  </g>
</svg>
'''


def main() -> None:
    out = Path(__file__).resolve().parent / "assets"
    out.mkdir(parents=True, exist_ok=True)
    for name, theme in (("hero-dark", DARK), ("hero-light", LIGHT)):
        path = out / f"{name}.svg"
        path.write_text(build(theme) + "\n", encoding="utf-8")
        print(f"wrote {path} ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
